name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      repo_owner: xenova
      commit_sha: 7bfc590f793a6281b87e56cd8b0819fe58a12014
      package: transformers.js
      path_to_docs: transformers.js/docs/source
      pre_command: cd transformers.js && npm install && npm run docs-api
      additional_args: --not_python_module
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
